### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by serayudigital** [aldyjrz/Gojek-Verification-Bypass#1]
[EdXposed_Modules_20200802_165126.txt](https://github.com/aldyjrz/Gojek-Verification-Bypass/files/5011935/EdXposed_Modules_20200802_165126.txt)
Load project, build, install setelah cek di log exposed module tdak jalan, error java class not found :D

**Comment by aldyjrz** [comment]
> [EdXposed_Modules_20200802_165126.txt](https://github.com/aldyjrz/Gojek-Verification-Bypass/files/5011935/EdXposed_Modules_20200802_165126.txt)
> Load project, build, install setelah cek di log exposed module tdak jalan, error java class not found :D

Silahkan gunakan gojek versi 421 agar tidak error karena belum support 422
